# Header metadata
url: ep.com

author: Dorota Komar

description_pl: desc pl
description_en: desc en

og_site_name_pl: pl
og_site_name_en: en

# Social media
social:
  facebook: https://facebook.com/x
  gplus   : https://plus.google.com/+S
  twitter : https://twitter.com/s
  youtube : https://youtube.com/S
  
  
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Warsaw

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:title/

# Struktura galerii
posts:
  "wpis1":
    "img": "p/a.jpg"
    "date": "1 Stycznia 2015"
    "title": "Tytul stycznia"
    "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed luctus semper felis, quis tincidunt orci molestie vel. Integer eu elit sit amet massa facilisis pharetra."
    
  "wpis2":
    "img": "p/a.jpg"
    "date": "2 Listopada 2014"
    "title": "Tytul wpisu"
    "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed luctus semper felis, quis tincidunt orci molestie vel. Integer eu elit sit amet massa facilisis pharetra."
    

